name: "auto-release."

on:
  push:
    - master

jobs:
  if: ${{ startsWith(github.ref, 'refs/tags/v*') }}
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
     
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootJar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*.jar
